services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: thoughts_board_backend
    volumes:
      - ./.env:/app/.env:ro
    environment:
      PORT: 8000
    depends_on:
      - db
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # ports:
    #   - "8000:8000"

  frontend:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile.frontend
    container_name: thoughts_board_frontend
    depends_on:
      - backend
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # ports:
    #   - "8080:80"

  db:
    image: postgres:16-alpine
    container_name: thoughts_board_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    # ports:
    #   - "5432:5432"

volumes:
  db_data: {}
