services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: thoughts_board_backend
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - app-network
    environment:
      PORT: 8000
    depends_on:
      - db
    restart: unless-stopped


  frontend:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile.frontend
    container_name: thoughts_board_frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped


  db:
    image: postgres:16-alpine
    container_name: thoughts_board_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  db_data: {}

networks:
    app-network: {}
