name: Docker CI/CD

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  # Имя образа будет ghcr.io/ВАШ_ЛОГИН/ВАШ_РЕПОЗИТОРИЙ-backend (и -frontend)
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # ===============================================
  # ЗАДАЧА №1: Сборка и публикация Docker-образов
  # ===============================================
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # Необходимо для cosign
    
    # Передаем теги наружу для следующей задачи
    outputs:
      backend_image: ${{ steps.push-backend.outputs.image }}
      frontend_image: ${{ steps.push-frontend.outputs.image }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- Сборка Backend образа ---
      - name: Extract Docker metadata for backend
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend

      - name: Build and push backend Docker image
        id: push-backend # Изменен id для ясности
        uses: docker/build-push-action@v5
        with:
          context: . # Убедитесь, что Dockerfile.backend в корне
          file: ./Dockerfile.backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_backend.outputs.tags }}
          labels: ${{ steps.meta_backend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- Сборка Frontend образа ---
      - name: Extract Docker metadata for frontend
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend

      - name: Build and push frontend Docker image
        id: push-frontend # Изменен id для ясности
        uses: docker/build-push-action@v5
        with:
          context: ./frontend-app # Убедитесь, что папка верна
          file: ./frontend-app/Dockerfile.frontend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_frontend.outputs.tags }}
          labels: ${{ steps.meta_frontend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- Подписание образов (опционально) ---
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.5.0

      - name: Sign the backend image
        if: github.event_name != 'pull_request'
        run: cosign sign --yes ${{ steps.push-backend.outputs.image }}@${{ steps.push-backend.outputs.digest }}

      - name: Sign the frontend image
        if: github.event_name != 'pull_request'
        run: cosign sign --yes ${{ steps.push-frontend.outputs.image }}@${{ steps.push-frontend.outputs.digest }}

  # ===============================================
  # ЗАДАЧА №2: Развертывание на сервере
  # ===============================================
  deploy:
    # Запускать эту задачу только после успешной сборки
    needs: build
    runs-on: ubuntu-latest
    
    # Запускать деплой только при push в master или по тегу, НЕ для pull-request
    if: github.event_name == 'push'

    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Переходим в папку проекта
            cd ~/thoughts
            
            # Логинимся в GitHub Container Registry с помощью Personal Access Token
            # Убедитесь, что секрет GHCR_PAT создан в настройках репозитория!
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Динамически обновляем docker-compose.yml новыми образами
            # Это надежнее, чем использовать теги
            sed -i 's|image: ghcr.io/.*-backend:.*|image: ${{ needs.build.outputs.backend_image }}|' docker-compose.yml
            sed -i 's|image: ghcr.io/.*-frontend:.*|image: ${{ needs.build.outputs.frontend_image }}|' docker-compose.yml
            
            # Скачиваем новые версии образов
            docker compose pull
            
            # Перезапускаем только обновленные сервисы
            docker compose up -d --no-deps backend frontend
            
            # Очищаем старые, неиспользуемые образы
            docker image prune -a -f
